config/routes.rb
Coursehub::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users

  match '/users/coursems' => 'users#coursems'

  resources :users
  resources :resources
  resources :events

  match '/events/recentevent/:id' => 'events#recentevent'

  match '/profile' => 'users#edit'
  match '/users/coursems' => 'users#coursems'
  match '/users/subscribe' => 'users#subscribe'
  match '/users/unsubscribe' => 'users#unsubscribe'
  match '/users/addFavorite' => 'users#addFavorite'
  match '/users/deleteFavorite' => 'users#deleteFavorite'

  match '/courses/show' => 'courses#show'
  match '/courses/department' => 'courses#getDepartment'
  match '/courses' => 'courses#index'
  match '/courses/check' => 'courses#checkSubscribed'
  match '/coursem/create' => 'coursem#create'
  match 'coursem/resources' => 'coursem#resources'

  match '/resources/addComment' => 'resources#addComment'
  match '/resources/type' => 'resources#getResourcesType'
  match '/resources/check' => 'resources#checkFavorite'
  match '/resources/flag' => 'resources#flag'
  match '/resources/unflag' => 'resources#unFlag'

  authenticated :user do
    root :to => "users#home"
  end
  root :to => redirect("/users/sign_in")

  resources :coursem

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar

  attr_accessible :name, :start_date, :end_date, :start_time,:end_time, :start_at, :end_at, :description,:coursem_id

  belongs_to :coursem, :inverse_of => :events

  ##############################
  def self.datetimefromobjects(d,t)
    DateTime.new(d.year, d.month, d.day, t.hour, t.min)
  end

  ##############################
  def self.datetimefromstrings(d,t)
    DateTime.new(getyearfromstring(d), getmonthfromstring(d), getdayfromstring(d), gethourfromstring(t), getminfromstring(t))
  end

  def self.getyearfromstring(date)
    d = date.split('-')
    d[0].to_i
  end
  def self.getmonthfromstring(date)
    d = date.split('-')
    d[1].to_i
  end
  def self.getdayfromstring(date)
    d = date.split('-')
    d[2].to_i
  end

  def self.gethourfromstring(t)
    pm = true
    if t[t.length-2..-1] == "am"
      pm = false
    end
    t = t[0..t.length-3]
    t = t.split(":")
    if pm
        result = t[0].to_i - 12
        result.to_i
    else
      t[0].to_i
    end
  end

  def self.getminfromstring(t)
    t = t[0..t.length-3]
    t = t.split(":")
    t[1].to_i
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
  end

  def show
    @event = Event.find(params[:id])
    render :partial => "event", :locals => {:event => @event}
  end

  def new
    @event = Event.new
    @coursem = Coursem.find(params[:coursem])
    render :partial => 'form'
  end

  def create
    @event = Event.new(params[:event])
    sdt = Event.datetimefromstrings(params[:event][:start_date], params[:event][:start_time])
    edt = Event.datetimefromstrings(params[:event][:end_date], params[:event][:end_time])
    @event.start_at = sdt
    @event.end_at = edt
    #if sdt == nil
    #  @event.start_at = edt - 1.minute
    #end
    respond_to do |format|
      if @event.save
        #flash[:notice] = "Successfully created event"
        format.js {}
      else
        format.js {render :partial => 'error' }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @coursem = Coursem.find(@event.coursem_id)
    render :partial => 'form', :locals => {:event => @event}
  end

  def update
    @event = Event.find(params[:id])
    sdt = Event.datetimefromstrings(params[:event][:start_date], params[:event][:start_time])
    edt = Event.datetimefromstrings(params[:event][:end_date], params[:event][:end_time])
    @event.start_at = sdt
    @event.end_at = edt
    @event.name = params[:event][:name]
    @event.start_date =  params[:event][:start_date]
    @event.start_time =  params[:event][:start_time]
    @event.end_date =  params[:event][:end_date]
    @event.end_time =  params[:event][:end_time]
    @event.description =  params[:event][:description]

    respond_to do |format|
      if @event.save
        format.js
      else
        format.js { render :partial => 'error' }
      end
    end
  end

  #checks if an event has happened in the past n seconds
  def recentevent
    @event = Event.find(params[:id])
    @updated_at = @event.updated_at
    @recent = false;
    if @updated_at - 10.seconds.ago > 0
      @recent = true;
    end

    respond_to do |format|
      format.json { render :json => @recent }
    end

  end

end

app/views/events/_event.html.erb
<div class="event-info">
    <table>
      <tr>
        <td>Event Name:</td>
        <td><%= @event.name %></td>
      </tr>
      <tr>
        <td>Start Date:</td>
        <td><%= @event.start_date %></td>
      </tr>
      <tr>
        <td>Start Time:</td>
        <td><%= @event.start_time.to_s.split[1] %></td>
      </tr>
      <tr>
        <td>End Date:</td>
        <td><%= @event.end_date%></td>
      </tr>
      <tr>
        <td>End Time:</td>
        <td><%= @event.end_time.to_s.split[1] %></td>
      </tr>
      <tr>
        <td>Description:</td>
        <td><%= @event.description %></td>
      </tr>
    </table>
  <%= link_to "Edit Event", edit_event_path(@event), :id => "edit_event"  %>
</div>

app/views/events/_form.html.erb
<div id="event_form" class='form-inline'>
    <%= form_for(@event, :remote=>true) do |f| %>
        <p>
          <%=  f.label :name %>
          <%=  f.text_field :name %>
        </p>
        <p>
          <%=  f.label :start_date %>
          <%=  f.text_field :start_date %>
        </p>
        <p>
          <%=  f.label :start_time %>
          <%=  f.text_field :start_time %>
        </p>
        <p>
          <%=  f.label :end_date %>
          <%=  f.text_field :end_date%>
        </p>
        <p>
          <%=  f.label :end_time %>
          <%=  f.text_field :end_time%>
        </p>
        <p>
          <%=  f.label :description %>
          <%=  f.text_area :description %>
        </p>
        <%= f.hidden_field :coursem_id, :value => @coursem.id %>
        <p><%=  f.submit :class=>"event_submit" %></p>
    <% end %>
</div>